### ISSUE TITLE
the cummulative sum curves are not plotted 

### ISSUE THREAD

**Issue by weblow0** [Baukebrenninkmeijer/table-evaluator#37]
when I run the table_evaluator.visualisation with my data real and fake generated using SMOTE all the curves can be plotted except the cummsum and I got the following type error:

TypeError: cdf() got an unexpected keyword argument 'local_ax'

**Comment by Baukebrenninkmeijer** [comment]
Without looking into in detail, it sounds like a mismatch between some library versions. What version of matplotlib and seaborn are you using?

**Comment by weblow0** [comment]
I am using matplotlib version 3.9.2
and seaborn version 0.13.2

**Comment by adgirban** [comment]
I have the same issue

**Comment by Baukebrenninkmeijer** [comment]
@adgirban @weblow0 Thanks for reporting this, guys. It seems it was my mistake, I'm deploying a fix at this moment.

**Comment by Baukebrenninkmeijer** [comment]
Please upgrade to the latest version and confirm that the issue is resolved :)

**Comment by adgirban** [comment]
there is still an issue with correlation plot/heatmap 
UserWarning:

set_ticklabels() should only be used with a fixed number of ticks, i.e. after set_ticks() or using a FixedLocator.

**Comment by Baukebrenninkmeijer** [comment]
@adgirban Indeed, but there are always UserWarnings. The functionality should be fine though. You can filter out the warnings yourself, should you desire so, using the warnings library.

**Comment by adgirban** [comment]
yeah but it still doesn't plot the heatmap among other plots
